# Generated by Django 4.2.4 on 2023-09-04 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, verbose_name='عنوان مقاله')),
                ('Title_en', models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله')),
                ('Title_fa', models.CharField(max_length=200, null=True, verbose_name='عنوان مقاله')),
                ('Slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس مقاله')),
                ('Description', models.TextField(verbose_name='توضیحات')),
                ('Description_en', models.TextField(null=True, verbose_name='توضیحات')),
                ('Description_fa', models.TextField(null=True, verbose_name='توضیحات')),
                ('Thumbnail', models.ImageField(upload_to='images', verbose_name='تصویر مقاله')),
                ('Publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان انتشار')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('is_spacial', models.BooleanField(default=False, verbose_name='مقاله ویژه')),
                ('Status', models.CharField(choices=[('d', 'پیشنویس'), ('p', 'منتشر شده'), ('i', 'در حال بررسی'), ('b', 'برگشت داده شده')], max_length=1, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
                'ordering': ['-Publish'],
            },
        ),
        migrations.CreateModel(
            name='IpAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(verbose_name='آدرس آیپی')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titles', models.CharField(max_length=200, verbose_name='عنوان دسته بندی')),
                ('slugs', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='آدرس دسته بندی')),
                ('statuses', models.BooleanField(default=True, verbose_name='آیا نمایش داده شود؟')),
                ('positions', models.IntegerField(verbose_name='پوزیشن')),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='زیر دسته')),
            ],
            options={
                'verbose_name': 'عنوان دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
                'ordering': ['parent__id', 'positions'],
            },
        ),
        migrations.CreateModel(
            name='ArticleHits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
                ('ip_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.ipaddress')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='Category',
            field=models.ManyToManyField(related_name='articles', to='blog.category', verbose_name='دسته بندی'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AddField(
            model_name='article',
            name='hits',
            field=models.ManyToManyField(blank=True, related_name='hits', through='blog.ArticleHits', to='blog.ipaddress', verbose_name='بازدیدها'),
        ),
    ]
