# Generated by Django 5.0.7 on 2024-07-26 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='titles_en',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان دسته بندی'),
        ),
        migrations.AddField(
            model_name='category',
            name='titles_fa',
            field=models.CharField(max_length=200, null=True, verbose_name='عنوان دسته بندی'),
        ),
    ]
