"""
Django settings for shop project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from django.utils.translation import gettext_lazy as _
import locale
# import environ
from pathlib import Path
import os
# from decouple import config
# env = environ.Env()
# environ.Env.read_env()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# redirect to home page . when the user is login
LOGIN_REDIRECT_URL = 'account:home'
LOGOUT_REDIRECT_URL = 'login'  # redirect to login page . when the user is logout
# redirect to login page . when the user want to going(see) the spacial page(the page need the login to open and see that)
LOGIN_URL = "login"

# http://127.0.0.1:8000/account/login/


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$d)+mknd3g+@&mmlq!_88sl2-(@x5=z^s=j1=z!n4sujsz+!#d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'modeltranslation',
    'blog.apps.BlogConfig',
    'django.contrib.admin',

    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 'payment.apps.PaymentConfig'
    'Extenshion',
    'crispy_forms',
    'widget_tweaks',
    'django_gravatar',
    'comment',
    'star_ratings',
    'django.contrib.humanize',
    # 'translated_fields',
    # 'azbankgateways', # درگاه بانکی
    # 'payment',

    "crispy_bootstrap5",
    'account.apps.AccountConfig',



]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'blog.middleware.SimpleMiddleware',
]

ROOT_URLCONF = 'shop.urls'
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        # going to root path templates
        'DIRS': [os.path.join(BASE_DIR, 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         # 'DIRS': [],
#         'DIRS': [os.path.join(BASE_DIR , 'templates'),],# going to root path templates
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#             ],
#         },
#     },
# ]

WSGI_APPLICATION = 'shop.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': 'fourth',
#         'USER': 'postgres',
#         'PORT': '5432',
#         'PASSWORD': '@12345678Hamedmoradi',
#         'HOST': '127.0.0.1',

#     }
# }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# gettext = lambda s: s
# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/
# IS_MONOLINGUAL=False
TRANSLATABLE_MODEL_MODULES = ["blog.models", "account.models", ]
LANGUAGE_CODE = 'fa'
LOCALE_PATHS = [BASE_DIR / 'locale']
# LOCALE_PATHS = (Path(BASE_DIR) / '../locale/', )
# locale.setlocale(locale.LC_ALL,"fa_IR.UTF-8")
# LOCAL_PATHS = [os.path.join(BASE_DIR, 'locale')]
TIME_ZONE = 'Asia/Tehran'
USE_I18N = True
USE_L10N = True
USE_TZ = True
LANGUAGES = [
    ('fa', _('Persian')),
    ('en', _('English')),
]
MODELTRANSLATION_DEFAULT_LANGUAGE = 'fa'
MODELTRANSLATION_LANGUAGES = ('en', 'fa')
MODELTRANSLATION_TRANSLATION_FILES = (
    'blog.translation',
    # '<APP2_MODULE>.translation',
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # اول اجرا بشع بعد کامنت
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),


    # os.path.join(BASE_DIR, "static/fontawesome"),
]


MEDIA_URL = '/MEDIA/'  # بخواییم برای عکسها و.. مسیر تعیین کنیم و بصورت خودکار نره جایی
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  # تعیین مسیر برای فایلهای استاتیک

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

CRISPY_TEMPLATE_PACK = "bootstrap5"

AUTH_USER_MODEL = 'account.User'

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'hameddjf106@gmail.com'
EMAIL_HOST_PASSWORD = 'aaas ypux cauw lbho'


STAR_RATINGS_STAR_HEIGHT = 20


def gettext(s): return s


# AZ_IRANIAN_BANK_GATEWAYS = {
#    'GATEWAYS': {
#        'BMI': {
#            'MERCHANT_CODE': '<YOUR MERCHANT CODE>',
#            'TERMINAL_CODE': '<YOUR TERMINAL CODE>',
#            'SECRET_KEY': '<YOUR SECRET CODE>',
#        },
#        'SEP': {
#            'MERCHANT_CODE': '<YOUR MERCHANT CODE>',
#            'TERMINAL_CODE': '<YOUR TERMINAL CODE>',
#        },
#     #    'ZARINPAL': {
#     #        'MERCHANT_CODE': 'cb70ca0f-a69a-47c8-852e-94b8ae5ce33b',
#     #        'SANDBOX': 1,  # 0 disable, 1 active
#     #    },
#        'IDPAY': {
#            'MERCHANT_CODE': 'ced73ac8-9ec9-40e6-aa47-08757df1be16',
#            'METHOD': 'POST',  # GET or POST
#            'X_SANDBOX': 1,  # 0 disable, 1 active
#        },
#        'BAHAMTA': {
#            'MERCHANT_CODE': 'd5a2b4ae-0552-4a10-aa95-338f810060a1:72085df4-6475-4fef-8df8-0f6da7934017',
#        },
#     #     'NEXTPAY': {
#     #        'MERCHANT_CODE': '88bf6ea5-8e2a-443b-9521-a6167351a511',
#     #    },
#    },
#    'IS_SAMPLE_FORM_ENABLE': True, # اختیاری و پیش فرض غیر فعال است
#    'DEFAULT': 'IDPAY',
#    'CURRENCY': 'IRR', # اختیاری
#    'TRACKING_CODE_QUERY_PARAM': 'tc', # اختیاری
#    'TRACKING_CODE_LENGTH': 16, # اختیاری
#    'SETTING_VALUE_READER_CLASS': 'azbankgateways.readers.DefaultReader', # اختیاری
#    'BANK_PRIORITIES': [
#        'BMI',
#        'SEP',
#    ], # اختیاری
#    'IS_SAFE_GET_GATEWAY_PAYMENT': False, #اختیاری، بهتر است True بزارید.
#    'CUSTOM_APP': None, # اختیاری
# }


# STAR_RATINGS_RERATE = False / اجازه تغییر رای پیشفرض میتونه تغییر بده
# STAR_RATINGS_RERATE_SAME_DELETE = True  / میتونه رایشو پس بگیره پیشفرض نمیتونه ... باید بالایی ری ریت فعال باشه تا اثر کنه
# STAR_RATINGS_ANONYMOUS = True / همه میتونن رای بدن پیشفرض فقط اونایی ک لاگین کردن
# STAR_RATINGS_RERATE, STAR_RATINGS_RERATE_SAME_DELETE and STAR_RATINGS_CLEARABLE  / غیر فعاله اینا فعالم باشن تاثیری نداره اثر ندارن این 3 تا.... تا وقتی ک انانیموس ترو بشه اثر میتونن بزارن STAR_RATINGS_ANONYMOUS وقتی
# STAR_RATINGS_RANGE / تغییر تعداد ستاره
# /static/star-ratings/images/stars.png / تغییر عکس یا شکل ستاره مانندش به ی شکل یا عکس دیگ
# star_ratings/widget.html / با ایجاد همچین مسیری میشه محتواهای نمایشی زیر شکل ستاره ای مثل میانگین و ... رو تغییر داد
